spring:
  application:
    name: taskflow
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow_user
    password: secretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  
